baseURL = 'https://arjunsajeevan.com/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'Arjun Sajeevan'
theme = 'PaperMod'

[params]
    env = "production"
    title = "Arjun Sajeevan"
    description = "Data Engineer @ Dell Technologies | ETL, SQL, PySpark"
    author = "Arjun Sajeevan"

    [params.profileMode]
        enabled = true
        title = "Arjun Sajeevan"
        subtitle = "Data Engineer at Dell Technologies. Specializing in ETL, SQL, and PySpark. Currently mastering Lakehouse architectures."
        
        [[params.profileMode.buttons]]
            name = "Posts"
            url = "/posts"
        [[params.profileMode.buttons]]
            name = "View Projects"
            url = "/projects"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/arjun-sajeevan"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/arjun-sajeevan-66634a167"